version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ssh
  webssh.cyrhades.fr:
    build: webssh
    ports:
    - ${PORT}:8888
  hyper-packer.cyrhades.fr:
    image: anssi/fcsc2022-reverse-hyper-packer:latest
    ports:
      - ${PORT_SSH}:4000